package com.fu.pums.domain;

<<<<<<< HEAD
import com.fasterxml.jackson.annotation.JsonIgnore;
=======
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

import javax.persistence.*;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * A Faculty.
 */
@Entity
@Table(name = "faculty")
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
public class Faculty implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "name")
    private String name;

<<<<<<< HEAD
=======
    @Column(name = "code")
    private String code;

>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
    @OneToMany(mappedBy = "faculty")
    @Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
    private Set<Student> students = new HashSet<>();

<<<<<<< HEAD
    @ManyToMany(mappedBy = "faculties")
    @Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
    @JsonIgnore
    private Set<Supervisor> supservisors = new HashSet<>();
=======
    @OneToMany(mappedBy = "faculty")
    @Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
    private Set<Project> projects = new HashSet<>();

    @OneToMany(mappedBy = "faculty")
    @Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
    private Set<Announcement> announcments = new HashSet<>();

    @ManyToMany
    @Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
    @JoinTable(name = "faculty_supervisors",
               joinColumns = @JoinColumn(name = "faculty_id", referencedColumnName = "id"),
               inverseJoinColumns = @JoinColumn(name = "supervisors_id", referencedColumnName = "id"))
    private Set<Supervisor> supervisors = new HashSet<>();
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity

    // jhipster-needle-entity-add-field - JHipster will add fields here
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public Faculty name(String name) {
        this.name = name;
        return this;
    }

    public void setName(String name) {
        this.name = name;
    }

<<<<<<< HEAD
=======
    public String getCode() {
        return code;
    }

    public Faculty code(String code) {
        this.code = code;
        return this;
    }

    public void setCode(String code) {
        this.code = code;
    }

>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
    public Set<Student> getStudents() {
        return students;
    }

    public Faculty students(Set<Student> students) {
        this.students = students;
        return this;
    }

<<<<<<< HEAD
    public Faculty addStudent(Student student) {
=======
    public Faculty addStudents(Student student) {
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
        this.students.add(student);
        student.setFaculty(this);
        return this;
    }

<<<<<<< HEAD
    public Faculty removeStudent(Student student) {
=======
    public Faculty removeStudents(Student student) {
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
        this.students.remove(student);
        student.setFaculty(null);
        return this;
    }

    public void setStudents(Set<Student> students) {
        this.students = students;
    }

<<<<<<< HEAD
    public Set<Supervisor> getSupservisors() {
        return supservisors;
    }

    public Faculty supservisors(Set<Supervisor> supervisors) {
        this.supservisors = supervisors;
        return this;
    }

    public Faculty addSupservisors(Supervisor supervisor) {
        this.supservisors.add(supervisor);
=======
    public Set<Project> getProjects() {
        return projects;
    }

    public Faculty projects(Set<Project> projects) {
        this.projects = projects;
        return this;
    }

    public Faculty addProjects(Project project) {
        this.projects.add(project);
        project.setFaculty(this);
        return this;
    }

    public Faculty removeProjects(Project project) {
        this.projects.remove(project);
        project.setFaculty(null);
        return this;
    }

    public void setProjects(Set<Project> projects) {
        this.projects = projects;
    }

    public Set<Announcement> getAnnouncments() {
        return announcments;
    }

    public Faculty announcments(Set<Announcement> announcements) {
        this.announcments = announcements;
        return this;
    }

    public Faculty addAnnouncments(Announcement announcement) {
        this.announcments.add(announcement);
        announcement.setFaculty(this);
        return this;
    }

    public Faculty removeAnnouncments(Announcement announcement) {
        this.announcments.remove(announcement);
        announcement.setFaculty(null);
        return this;
    }

    public void setAnnouncments(Set<Announcement> announcements) {
        this.announcments = announcements;
    }

    public Set<Supervisor> getSupervisors() {
        return supervisors;
    }

    public Faculty supervisors(Set<Supervisor> supervisors) {
        this.supervisors = supervisors;
        return this;
    }

    public Faculty addSupervisors(Supervisor supervisor) {
        this.supervisors.add(supervisor);
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
        supervisor.getFaculties().add(this);
        return this;
    }

<<<<<<< HEAD
    public Faculty removeSupservisors(Supervisor supervisor) {
        this.supservisors.remove(supervisor);
=======
    public Faculty removeSupervisors(Supervisor supervisor) {
        this.supervisors.remove(supervisor);
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
        supervisor.getFaculties().remove(this);
        return this;
    }

<<<<<<< HEAD
    public void setSupservisors(Set<Supervisor> supervisors) {
        this.supservisors = supervisors;
=======
    public void setSupervisors(Set<Supervisor> supervisors) {
        this.supervisors = supervisors;
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
    }
    // jhipster-needle-entity-add-getters-setters - JHipster will add getters and setters here

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof Faculty)) {
            return false;
        }
        return id != null && id.equals(((Faculty) o).id);
    }

    @Override
    public int hashCode() {
        return 31;
    }

    // prettier-ignore
    @Override
    public String toString() {
        return "Faculty{" +
            "id=" + getId() +
            ", name='" + getName() + "'" +
<<<<<<< HEAD
=======
            ", code='" + getCode() + "'" +
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
            "}";
    }
}
