package com.fu.pums.domain;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

import javax.persistence.*;

import java.io.Serializable;
import java.time.Instant;

/**
 * A File.
 */
@Entity
@Table(name = "file")
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
public class File implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "name")
    private String name;

    @Lob
    @Column(name = "file")
    private byte[] file;

    @Column(name = "file_content_type")
    private String fileContentType;

<<<<<<< HEAD
    @Column(name = "date")
    private Instant date;
=======
    @Column(name = "upload_date")
    private Instant uploadDate;
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity

    @Column(name = "type")
    private String type;

    @OneToOne(mappedBy = "file")
    @JsonIgnore
<<<<<<< HEAD
    private ResultData resultData;
=======
    private Observation observation;
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity

    @ManyToOne
    @JsonIgnoreProperties(value = "files", allowSetters = true)
    private Project project;

    // jhipster-needle-entity-add-field - JHipster will add fields here
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public File name(String name) {
        this.name = name;
        return this;
    }

    public void setName(String name) {
        this.name = name;
    }

    public byte[] getFile() {
        return file;
    }

    public File file(byte[] file) {
        this.file = file;
        return this;
    }

    public void setFile(byte[] file) {
        this.file = file;
    }

    public String getFileContentType() {
        return fileContentType;
    }

    public File fileContentType(String fileContentType) {
        this.fileContentType = fileContentType;
        return this;
    }

    public void setFileContentType(String fileContentType) {
        this.fileContentType = fileContentType;
    }

<<<<<<< HEAD
    public Instant getDate() {
        return date;
    }

    public File date(Instant date) {
        this.date = date;
        return this;
    }

    public void setDate(Instant date) {
        this.date = date;
=======
    public Instant getUploadDate() {
        return uploadDate;
    }

    public File uploadDate(Instant uploadDate) {
        this.uploadDate = uploadDate;
        return this;
    }

    public void setUploadDate(Instant uploadDate) {
        this.uploadDate = uploadDate;
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
    }

    public String getType() {
        return type;
    }

    public File type(String type) {
        this.type = type;
        return this;
    }

    public void setType(String type) {
        this.type = type;
    }

<<<<<<< HEAD
    public ResultData getResultData() {
        return resultData;
    }

    public File resultData(ResultData resultData) {
        this.resultData = resultData;
        return this;
    }

    public void setResultData(ResultData resultData) {
        this.resultData = resultData;
=======
    public Observation getObservation() {
        return observation;
    }

    public File observation(Observation observation) {
        this.observation = observation;
        return this;
    }

    public void setObservation(Observation observation) {
        this.observation = observation;
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
    }

    public Project getProject() {
        return project;
    }

    public File project(Project project) {
        this.project = project;
        return this;
    }

    public void setProject(Project project) {
        this.project = project;
    }
    // jhipster-needle-entity-add-getters-setters - JHipster will add getters and setters here

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof File)) {
            return false;
        }
        return id != null && id.equals(((File) o).id);
    }

    @Override
    public int hashCode() {
        return 31;
    }

    // prettier-ignore
    @Override
    public String toString() {
        return "File{" +
            "id=" + getId() +
            ", name='" + getName() + "'" +
            ", file='" + getFile() + "'" +
            ", fileContentType='" + getFileContentType() + "'" +
<<<<<<< HEAD
            ", date='" + getDate() + "'" +
=======
            ", uploadDate='" + getUploadDate() + "'" +
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
            ", type='" + getType() + "'" +
            "}";
    }
}
