package com.fu.pums.repository;

import com.fu.pums.domain.Announcement;

import org.springframework.data.jpa.repository.*;
import org.springframework.stereotype.Repository;

/**
 * Spring Data  repository for the Announcement entity.
 */
@SuppressWarnings("unused")
@Repository
<<<<<<< HEAD
public interface AnnouncementRepository extends JpaRepository<Announcement, Long> {
=======
public interface AnnouncementRepository extends JpaRepository<Announcement, Long>, JpaSpecificationExecutor<Announcement> {
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
}
