package com.fu.pums.repository;

import com.fu.pums.domain.File;

import org.springframework.data.jpa.repository.*;
import org.springframework.stereotype.Repository;

/**
 * Spring Data  repository for the File entity.
 */
@SuppressWarnings("unused")
@Repository
<<<<<<< HEAD
public interface FileRepository extends JpaRepository<File, Long> {
=======
public interface FileRepository extends JpaRepository<File, Long>, JpaSpecificationExecutor<File> {
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
}
