package com.fu.pums.repository;

import com.fu.pums.domain.Project;

import org.springframework.data.jpa.repository.*;
import org.springframework.stereotype.Repository;

/**
 * Spring Data  repository for the Project entity.
 */
@SuppressWarnings("unused")
@Repository
<<<<<<< HEAD
public interface ProjectRepository extends JpaRepository<Project, Long> {
=======
public interface ProjectRepository extends JpaRepository<Project, Long>, JpaSpecificationExecutor<Project> {
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
}
