package com.fu.pums.repository;

import com.fu.pums.domain.Student;

import org.springframework.data.jpa.repository.*;
import org.springframework.stereotype.Repository;

/**
 * Spring Data  repository for the Student entity.
 */
@SuppressWarnings("unused")
@Repository
<<<<<<< HEAD
public interface StudentRepository extends JpaRepository<Student, Long> {
=======
public interface StudentRepository extends JpaRepository<Student, Long>, JpaSpecificationExecutor<Student> {
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
}
