import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { JhiDataUtils, JhiFileLoadError, JhiEventManager, JhiEventWithContent } from 'ng-jhipster';

import { IAnnouncement, Announcement } from 'app/shared/model/announcement.model';
import { AnnouncementService } from './announcement.service';
import { AlertError } from 'app/shared/alert/alert-error.model';
<<<<<<< HEAD
import { IPhase } from 'app/shared/model/phase.model';
import { PhaseService } from 'app/entities/phase/phase.service';
=======
import { IFaculty } from 'app/shared/model/faculty.model';
import { FacultyService } from 'app/entities/faculty/faculty.service';
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity

@Component({
  selector: 'jhi-announcement-update',
  templateUrl: './announcement-update.component.html',
})
export class AnnouncementUpdateComponent implements OnInit {
  isSaving = false;
<<<<<<< HEAD
  phases: IPhase[] = [];
=======
  faculties: IFaculty[] = [];
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
  startDateDp: any;
  endDateDp: any;

  editForm = this.fb.group({
    id: [],
<<<<<<< HEAD
=======
    title: [],
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
    content: [],
    announcmentType: [],
    startDate: [],
    endDate: [],
<<<<<<< HEAD
    phase: [],
=======
    faculty: [],
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
  });

  constructor(
    protected dataUtils: JhiDataUtils,
    protected eventManager: JhiEventManager,
    protected announcementService: AnnouncementService,
<<<<<<< HEAD
    protected phaseService: PhaseService,
=======
    protected facultyService: FacultyService,
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ announcement }) => {
      this.updateForm(announcement);

<<<<<<< HEAD
      this.phaseService.query().subscribe((res: HttpResponse<IPhase[]>) => (this.phases = res.body || []));
=======
      this.facultyService.query().subscribe((res: HttpResponse<IFaculty[]>) => (this.faculties = res.body || []));
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
    });
  }

  updateForm(announcement: IAnnouncement): void {
    this.editForm.patchValue({
      id: announcement.id,
<<<<<<< HEAD
=======
      title: announcement.title,
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
      content: announcement.content,
      announcmentType: announcement.announcmentType,
      startDate: announcement.startDate,
      endDate: announcement.endDate,
<<<<<<< HEAD
      phase: announcement.phase,
=======
      faculty: announcement.faculty,
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
    });
  }

  byteSize(base64String: string): string {
    return this.dataUtils.byteSize(base64String);
  }

  openFile(contentType: string, base64String: string): void {
    this.dataUtils.openFile(contentType, base64String);
  }

  setFileData(event: any, field: string, isImage: boolean): void {
    this.dataUtils.loadFileToForm(event, this.editForm, field, isImage).subscribe(null, (err: JhiFileLoadError) => {
      this.eventManager.broadcast(
        new JhiEventWithContent<AlertError>('pumsApp.error', { ...err, key: 'error.file.' + err.key })
      );
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const announcement = this.createFromForm();
    if (announcement.id !== undefined) {
      this.subscribeToSaveResponse(this.announcementService.update(announcement));
    } else {
      this.subscribeToSaveResponse(this.announcementService.create(announcement));
    }
  }

  private createFromForm(): IAnnouncement {
    return {
      ...new Announcement(),
      id: this.editForm.get(['id'])!.value,
<<<<<<< HEAD
=======
      title: this.editForm.get(['title'])!.value,
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
      content: this.editForm.get(['content'])!.value,
      announcmentType: this.editForm.get(['announcmentType'])!.value,
      startDate: this.editForm.get(['startDate'])!.value,
      endDate: this.editForm.get(['endDate'])!.value,
<<<<<<< HEAD
      phase: this.editForm.get(['phase'])!.value,
=======
      faculty: this.editForm.get(['faculty'])!.value,
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IAnnouncement>>): void {
    result.subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError(): void {
    this.isSaving = false;
  }

<<<<<<< HEAD
  trackById(index: number, item: IPhase): any {
=======
  trackById(index: number, item: IFaculty): any {
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
    return item.id;
  }
}
