import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { JhiDataUtils, JhiFileLoadError, JhiEventManager, JhiEventWithContent } from 'ng-jhipster';

import { IProject, Project } from 'app/shared/model/project.model';
import { ProjectService } from './project.service';
import { AlertError } from 'app/shared/alert/alert-error.model';
<<<<<<< HEAD
=======
import { IFaculty } from 'app/shared/model/faculty.model';
import { FacultyService } from 'app/entities/faculty/faculty.service';
import { ISupervisor } from 'app/shared/model/supervisor.model';
import { SupervisorService } from 'app/entities/supervisor/supervisor.service';

type SelectableEntity = IFaculty | ISupervisor;
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity

@Component({
  selector: 'jhi-project-update',
  templateUrl: './project-update.component.html',
})
export class ProjectUpdateComponent implements OnInit {
  isSaving = false;
<<<<<<< HEAD
=======
  faculties: IFaculty[] = [];
  supervisors: ISupervisor[] = [];
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity

  editForm = this.fb.group({
    id: [],
    name: [],
<<<<<<< HEAD
    detials: [],
    objective: [],
    problem: [],
=======
    details: [],
    objectives: [],
    problems: [],
    faculty: [],
    supervisor: [],
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
  });

  constructor(
    protected dataUtils: JhiDataUtils,
    protected eventManager: JhiEventManager,
    protected projectService: ProjectService,
<<<<<<< HEAD
=======
    protected facultyService: FacultyService,
    protected supervisorService: SupervisorService,
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ project }) => {
      this.updateForm(project);
<<<<<<< HEAD
=======

      this.facultyService.query().subscribe((res: HttpResponse<IFaculty[]>) => (this.faculties = res.body || []));

      this.supervisorService.query().subscribe((res: HttpResponse<ISupervisor[]>) => (this.supervisors = res.body || []));
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
    });
  }

  updateForm(project: IProject): void {
    this.editForm.patchValue({
      id: project.id,
      name: project.name,
<<<<<<< HEAD
      detials: project.detials,
      objective: project.objective,
      problem: project.problem,
=======
      details: project.details,
      objectives: project.objectives,
      problems: project.problems,
      faculty: project.faculty,
      supervisor: project.supervisor,
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
    });
  }

  byteSize(base64String: string): string {
    return this.dataUtils.byteSize(base64String);
  }

  openFile(contentType: string, base64String: string): void {
    this.dataUtils.openFile(contentType, base64String);
  }

  setFileData(event: any, field: string, isImage: boolean): void {
    this.dataUtils.loadFileToForm(event, this.editForm, field, isImage).subscribe(null, (err: JhiFileLoadError) => {
      this.eventManager.broadcast(
        new JhiEventWithContent<AlertError>('pumsApp.error', { ...err, key: 'error.file.' + err.key })
      );
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const project = this.createFromForm();
    if (project.id !== undefined) {
      this.subscribeToSaveResponse(this.projectService.update(project));
    } else {
      this.subscribeToSaveResponse(this.projectService.create(project));
    }
  }

  private createFromForm(): IProject {
    return {
      ...new Project(),
      id: this.editForm.get(['id'])!.value,
      name: this.editForm.get(['name'])!.value,
<<<<<<< HEAD
      detials: this.editForm.get(['detials'])!.value,
      objective: this.editForm.get(['objective'])!.value,
      problem: this.editForm.get(['problem'])!.value,
=======
      details: this.editForm.get(['details'])!.value,
      objectives: this.editForm.get(['objectives'])!.value,
      problems: this.editForm.get(['problems'])!.value,
      faculty: this.editForm.get(['faculty'])!.value,
      supervisor: this.editForm.get(['supervisor'])!.value,
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IProject>>): void {
    result.subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError(): void {
    this.isSaving = false;
  }
<<<<<<< HEAD
=======

  trackById(index: number, item: SelectableEntity): any {
    return item.id;
  }
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
}
