export const enum AnnouncementType {
  SUBMISSION = 'SUBMISSION',

  DISCUSSIONS = 'DISCUSSIONS',

  OBSERVATIONS = 'OBSERVATIONS',
<<<<<<< HEAD
=======

  OTHERS = 'OTHERS',
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
}
