import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';

import { IFaculty, Faculty } from 'app/shared/model/faculty.model';
import { FacultyService } from './faculty.service';
<<<<<<< HEAD
=======
import { ISupervisor } from 'app/shared/model/supervisor.model';
import { SupervisorService } from 'app/entities/supervisor/supervisor.service';
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity

@Component({
  selector: 'jhi-faculty-update',
  templateUrl: './faculty-update.component.html',
})
export class FacultyUpdateComponent implements OnInit {
  isSaving = false;
<<<<<<< HEAD
=======
  supervisors: ISupervisor[] = [];
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity

  editForm = this.fb.group({
    id: [],
    name: [],
<<<<<<< HEAD
  });

  constructor(protected facultyService: FacultyService, protected activatedRoute: ActivatedRoute, private fb: FormBuilder) {}
=======
    code: [],
    supervisors: [],
  });

  constructor(
    protected facultyService: FacultyService,
    protected supervisorService: SupervisorService,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ faculty }) => {
      this.updateForm(faculty);
<<<<<<< HEAD
=======

      this.supervisorService.query().subscribe((res: HttpResponse<ISupervisor[]>) => (this.supervisors = res.body || []));
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
    });
  }

  updateForm(faculty: IFaculty): void {
    this.editForm.patchValue({
      id: faculty.id,
      name: faculty.name,
<<<<<<< HEAD
=======
      code: faculty.code,
      supervisors: faculty.supervisors,
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const faculty = this.createFromForm();
    if (faculty.id !== undefined) {
      this.subscribeToSaveResponse(this.facultyService.update(faculty));
    } else {
      this.subscribeToSaveResponse(this.facultyService.create(faculty));
    }
  }

  private createFromForm(): IFaculty {
    return {
      ...new Faculty(),
      id: this.editForm.get(['id'])!.value,
      name: this.editForm.get(['name'])!.value,
<<<<<<< HEAD
=======
      code: this.editForm.get(['code'])!.value,
      supervisors: this.editForm.get(['supervisors'])!.value,
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IFaculty>>): void {
    result.subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError(): void {
    this.isSaving = false;
  }
<<<<<<< HEAD
=======

  trackById(index: number, item: ISupervisor): any {
    return item.id;
  }

  getSelected(selectedVals: ISupervisor[], option: ISupervisor): ISupervisor {
    if (selectedVals) {
      for (let i = 0; i < selectedVals.length; i++) {
        if (option.id === selectedVals[i].id) {
          return selectedVals[i];
        }
      }
    }
    return option;
  }
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
}
