import { Moment } from 'moment';
<<<<<<< HEAD
import { IPhase } from 'app/shared/model/phase.model';
=======
import { IFaculty } from 'app/shared/model/faculty.model';
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
import { AnnouncementType } from 'app/shared/model/enumerations/announcement-type.model';

export interface IAnnouncement {
  id?: number;
<<<<<<< HEAD
=======
  title?: string;
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
  content?: any;
  announcmentType?: AnnouncementType;
  startDate?: Moment;
  endDate?: Moment;
<<<<<<< HEAD
  phase?: IPhase;
=======
  faculty?: IFaculty;
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
}

export class Announcement implements IAnnouncement {
  constructor(
    public id?: number,
<<<<<<< HEAD
=======
    public title?: string,
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
    public content?: any,
    public announcmentType?: AnnouncementType,
    public startDate?: Moment,
    public endDate?: Moment,
<<<<<<< HEAD
    public phase?: IPhase
=======
    public faculty?: IFaculty
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
  ) {}
}
