import { Moment } from 'moment';
<<<<<<< HEAD
import { IResultData } from 'app/shared/model/result-data.model';
=======
import { IObservation } from 'app/shared/model/observation.model';
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
import { IProject } from 'app/shared/model/project.model';

export interface IFile {
  id?: number;
  name?: string;
  fileContentType?: string;
  file?: any;
<<<<<<< HEAD
  date?: Moment;
  type?: string;
  resultData?: IResultData;
=======
  uploadDate?: Moment;
  type?: string;
  observation?: IObservation;
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
  project?: IProject;
}

export class File implements IFile {
  constructor(
    public id?: number,
    public name?: string,
    public fileContentType?: string,
    public file?: any,
<<<<<<< HEAD
    public date?: Moment,
    public type?: string,
    public resultData?: IResultData,
=======
    public uploadDate?: Moment,
    public type?: string,
    public observation?: IObservation,
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
    public project?: IProject
  ) {}
}
