<<<<<<< HEAD
import { IFaculty } from 'app/shared/model/faculty.model';

export interface ISupervisor {
  id?: number;
  phoneNumber?: string;
=======
import { IProject } from 'app/shared/model/project.model';
import { IFaculty } from 'app/shared/model/faculty.model';
import { Gender } from 'app/shared/model/enumerations/gender.model';

export interface ISupervisor {
  id?: number;
  fullName?: string;
  role?: string;
  gender?: Gender;
  email?: string;
  phoneNumber?: string;
  projects?: IProject[];
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
  faculties?: IFaculty[];
}

export class Supervisor implements ISupervisor {
<<<<<<< HEAD
  constructor(public id?: number, public phoneNumber?: string, public faculties?: IFaculty[]) {}
=======
  constructor(
    public id?: number,
    public fullName?: string,
    public role?: string,
    public gender?: Gender,
    public email?: string,
    public phoneNumber?: string,
    public projects?: IProject[],
    public faculties?: IFaculty[]
  ) {}
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
}
