package com.fu.pums.domain.enumeration;

/**
 * The AnnouncementType enumeration.
 */
public enum AnnouncementType {
<<<<<<< HEAD
    SUBMISSION, DISCUSSIONS, OBSERVATIONS
=======
    SUBMISSION, DISCUSSIONS, OBSERVATIONS, OTHERS
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
}
