package com.fu.pums.web.rest;

import com.fu.pums.PumsApp;
import com.fu.pums.domain.Project;
<<<<<<< HEAD
import com.fu.pums.repository.ProjectRepository;
import com.fu.pums.service.ProjectService;
=======
import com.fu.pums.domain.Student;
import com.fu.pums.domain.File;
import com.fu.pums.domain.Observation;
import com.fu.pums.domain.Faculty;
import com.fu.pums.domain.Supervisor;
import com.fu.pums.repository.ProjectRepository;
import com.fu.pums.service.ProjectService;
import com.fu.pums.service.dto.ProjectCriteria;
import com.fu.pums.service.ProjectQueryService;
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.security.test.context.support.WithMockUser;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.Base64Utils;
import javax.persistence.EntityManager;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.hamcrest.Matchers.hasItem;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

/**
 * Integration tests for the {@link ProjectResource} REST controller.
 */
@SpringBootTest(classes = PumsApp.class)
@AutoConfigureMockMvc
@WithMockUser
public class ProjectResourceIT {

    private static final String DEFAULT_NAME = "AAAAAAAAAA";
    private static final String UPDATED_NAME = "BBBBBBBBBB";

<<<<<<< HEAD
    private static final String DEFAULT_DETIALS = "AAAAAAAAAA";
    private static final String UPDATED_DETIALS = "BBBBBBBBBB";

    private static final String DEFAULT_OBJECTIVE = "AAAAAAAAAA";
    private static final String UPDATED_OBJECTIVE = "BBBBBBBBBB";

    private static final String DEFAULT_PROBLEM = "AAAAAAAAAA";
    private static final String UPDATED_PROBLEM = "BBBBBBBBBB";
=======
    private static final String DEFAULT_DETAILS = "AAAAAAAAAA";
    private static final String UPDATED_DETAILS = "BBBBBBBBBB";

    private static final String DEFAULT_OBJECTIVES = "AAAAAAAAAA";
    private static final String UPDATED_OBJECTIVES = "BBBBBBBBBB";

    private static final String DEFAULT_PROBLEMS = "AAAAAAAAAA";
    private static final String UPDATED_PROBLEMS = "BBBBBBBBBB";
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity

    @Autowired
    private ProjectRepository projectRepository;

    @Autowired
    private ProjectService projectService;

    @Autowired
<<<<<<< HEAD
=======
    private ProjectQueryService projectQueryService;

    @Autowired
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
    private EntityManager em;

    @Autowired
    private MockMvc restProjectMockMvc;

    private Project project;

    /**
     * Create an entity for this test.
     *
     * This is a static method, as tests for other entities might also need it,
     * if they test an entity which requires the current entity.
     */
    public static Project createEntity(EntityManager em) {
        Project project = new Project()
            .name(DEFAULT_NAME)
<<<<<<< HEAD
            .detials(DEFAULT_DETIALS)
            .objective(DEFAULT_OBJECTIVE)
            .problem(DEFAULT_PROBLEM);
=======
            .details(DEFAULT_DETAILS)
            .objectives(DEFAULT_OBJECTIVES)
            .problems(DEFAULT_PROBLEMS);
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
        return project;
    }
    /**
     * Create an updated entity for this test.
     *
     * This is a static method, as tests for other entities might also need it,
     * if they test an entity which requires the current entity.
     */
    public static Project createUpdatedEntity(EntityManager em) {
        Project project = new Project()
            .name(UPDATED_NAME)
<<<<<<< HEAD
            .detials(UPDATED_DETIALS)
            .objective(UPDATED_OBJECTIVE)
            .problem(UPDATED_PROBLEM);
=======
            .details(UPDATED_DETAILS)
            .objectives(UPDATED_OBJECTIVES)
            .problems(UPDATED_PROBLEMS);
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
        return project;
    }

    @BeforeEach
    public void initTest() {
        project = createEntity(em);
    }

    @Test
    @Transactional
    public void createProject() throws Exception {
        int databaseSizeBeforeCreate = projectRepository.findAll().size();
        // Create the Project
        restProjectMockMvc.perform(post("/api/projects")
            .contentType(MediaType.APPLICATION_JSON)
            .content(TestUtil.convertObjectToJsonBytes(project)))
            .andExpect(status().isCreated());

        // Validate the Project in the database
        List<Project> projectList = projectRepository.findAll();
        assertThat(projectList).hasSize(databaseSizeBeforeCreate + 1);
        Project testProject = projectList.get(projectList.size() - 1);
        assertThat(testProject.getName()).isEqualTo(DEFAULT_NAME);
<<<<<<< HEAD
        assertThat(testProject.getDetials()).isEqualTo(DEFAULT_DETIALS);
        assertThat(testProject.getObjective()).isEqualTo(DEFAULT_OBJECTIVE);
        assertThat(testProject.getProblem()).isEqualTo(DEFAULT_PROBLEM);
=======
        assertThat(testProject.getDetails()).isEqualTo(DEFAULT_DETAILS);
        assertThat(testProject.getObjectives()).isEqualTo(DEFAULT_OBJECTIVES);
        assertThat(testProject.getProblems()).isEqualTo(DEFAULT_PROBLEMS);
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
    }

    @Test
    @Transactional
    public void createProjectWithExistingId() throws Exception {
        int databaseSizeBeforeCreate = projectRepository.findAll().size();

        // Create the Project with an existing ID
        project.setId(1L);

        // An entity with an existing ID cannot be created, so this API call must fail
        restProjectMockMvc.perform(post("/api/projects")
            .contentType(MediaType.APPLICATION_JSON)
            .content(TestUtil.convertObjectToJsonBytes(project)))
            .andExpect(status().isBadRequest());

        // Validate the Project in the database
        List<Project> projectList = projectRepository.findAll();
        assertThat(projectList).hasSize(databaseSizeBeforeCreate);
    }


    @Test
    @Transactional
    public void getAllProjects() throws Exception {
        // Initialize the database
        projectRepository.saveAndFlush(project);

        // Get all the projectList
        restProjectMockMvc.perform(get("/api/projects?sort=id,desc"))
            .andExpect(status().isOk())
            .andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
            .andExpect(jsonPath("$.[*].id").value(hasItem(project.getId().intValue())))
            .andExpect(jsonPath("$.[*].name").value(hasItem(DEFAULT_NAME)))
<<<<<<< HEAD
            .andExpect(jsonPath("$.[*].detials").value(hasItem(DEFAULT_DETIALS.toString())))
            .andExpect(jsonPath("$.[*].objective").value(hasItem(DEFAULT_OBJECTIVE.toString())))
            .andExpect(jsonPath("$.[*].problem").value(hasItem(DEFAULT_PROBLEM.toString())));
=======
            .andExpect(jsonPath("$.[*].details").value(hasItem(DEFAULT_DETAILS.toString())))
            .andExpect(jsonPath("$.[*].objectives").value(hasItem(DEFAULT_OBJECTIVES.toString())))
            .andExpect(jsonPath("$.[*].problems").value(hasItem(DEFAULT_PROBLEMS.toString())));
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
    }
    
    @Test
    @Transactional
    public void getProject() throws Exception {
        // Initialize the database
        projectRepository.saveAndFlush(project);

        // Get the project
        restProjectMockMvc.perform(get("/api/projects/{id}", project.getId()))
            .andExpect(status().isOk())
            .andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
            .andExpect(jsonPath("$.id").value(project.getId().intValue()))
            .andExpect(jsonPath("$.name").value(DEFAULT_NAME))
<<<<<<< HEAD
            .andExpect(jsonPath("$.detials").value(DEFAULT_DETIALS.toString()))
            .andExpect(jsonPath("$.objective").value(DEFAULT_OBJECTIVE.toString()))
            .andExpect(jsonPath("$.problem").value(DEFAULT_PROBLEM.toString()));
    }
=======
            .andExpect(jsonPath("$.details").value(DEFAULT_DETAILS.toString()))
            .andExpect(jsonPath("$.objectives").value(DEFAULT_OBJECTIVES.toString()))
            .andExpect(jsonPath("$.problems").value(DEFAULT_PROBLEMS.toString()));
    }


    @Test
    @Transactional
    public void getProjectsByIdFiltering() throws Exception {
        // Initialize the database
        projectRepository.saveAndFlush(project);

        Long id = project.getId();

        defaultProjectShouldBeFound("id.equals=" + id);
        defaultProjectShouldNotBeFound("id.notEquals=" + id);

        defaultProjectShouldBeFound("id.greaterThanOrEqual=" + id);
        defaultProjectShouldNotBeFound("id.greaterThan=" + id);

        defaultProjectShouldBeFound("id.lessThanOrEqual=" + id);
        defaultProjectShouldNotBeFound("id.lessThan=" + id);
    }


    @Test
    @Transactional
    public void getAllProjectsByNameIsEqualToSomething() throws Exception {
        // Initialize the database
        projectRepository.saveAndFlush(project);

        // Get all the projectList where name equals to DEFAULT_NAME
        defaultProjectShouldBeFound("name.equals=" + DEFAULT_NAME);

        // Get all the projectList where name equals to UPDATED_NAME
        defaultProjectShouldNotBeFound("name.equals=" + UPDATED_NAME);
    }

    @Test
    @Transactional
    public void getAllProjectsByNameIsNotEqualToSomething() throws Exception {
        // Initialize the database
        projectRepository.saveAndFlush(project);

        // Get all the projectList where name not equals to DEFAULT_NAME
        defaultProjectShouldNotBeFound("name.notEquals=" + DEFAULT_NAME);

        // Get all the projectList where name not equals to UPDATED_NAME
        defaultProjectShouldBeFound("name.notEquals=" + UPDATED_NAME);
    }

    @Test
    @Transactional
    public void getAllProjectsByNameIsInShouldWork() throws Exception {
        // Initialize the database
        projectRepository.saveAndFlush(project);

        // Get all the projectList where name in DEFAULT_NAME or UPDATED_NAME
        defaultProjectShouldBeFound("name.in=" + DEFAULT_NAME + "," + UPDATED_NAME);

        // Get all the projectList where name equals to UPDATED_NAME
        defaultProjectShouldNotBeFound("name.in=" + UPDATED_NAME);
    }

    @Test
    @Transactional
    public void getAllProjectsByNameIsNullOrNotNull() throws Exception {
        // Initialize the database
        projectRepository.saveAndFlush(project);

        // Get all the projectList where name is not null
        defaultProjectShouldBeFound("name.specified=true");

        // Get all the projectList where name is null
        defaultProjectShouldNotBeFound("name.specified=false");
    }
                @Test
    @Transactional
    public void getAllProjectsByNameContainsSomething() throws Exception {
        // Initialize the database
        projectRepository.saveAndFlush(project);

        // Get all the projectList where name contains DEFAULT_NAME
        defaultProjectShouldBeFound("name.contains=" + DEFAULT_NAME);

        // Get all the projectList where name contains UPDATED_NAME
        defaultProjectShouldNotBeFound("name.contains=" + UPDATED_NAME);
    }

    @Test
    @Transactional
    public void getAllProjectsByNameNotContainsSomething() throws Exception {
        // Initialize the database
        projectRepository.saveAndFlush(project);

        // Get all the projectList where name does not contain DEFAULT_NAME
        defaultProjectShouldNotBeFound("name.doesNotContain=" + DEFAULT_NAME);

        // Get all the projectList where name does not contain UPDATED_NAME
        defaultProjectShouldBeFound("name.doesNotContain=" + UPDATED_NAME);
    }


    @Test
    @Transactional
    public void getAllProjectsByStudentsIsEqualToSomething() throws Exception {
        // Initialize the database
        projectRepository.saveAndFlush(project);
        Student students = StudentResourceIT.createEntity(em);
        em.persist(students);
        em.flush();
        project.addStudents(students);
        projectRepository.saveAndFlush(project);
        Long studentsId = students.getId();

        // Get all the projectList where students equals to studentsId
        defaultProjectShouldBeFound("studentsId.equals=" + studentsId);

        // Get all the projectList where students equals to studentsId + 1
        defaultProjectShouldNotBeFound("studentsId.equals=" + (studentsId + 1));
    }


    @Test
    @Transactional
    public void getAllProjectsByFilesIsEqualToSomething() throws Exception {
        // Initialize the database
        projectRepository.saveAndFlush(project);
        File files = FileResourceIT.createEntity(em);
        em.persist(files);
        em.flush();
        project.addFiles(files);
        projectRepository.saveAndFlush(project);
        Long filesId = files.getId();

        // Get all the projectList where files equals to filesId
        defaultProjectShouldBeFound("filesId.equals=" + filesId);

        // Get all the projectList where files equals to filesId + 1
        defaultProjectShouldNotBeFound("filesId.equals=" + (filesId + 1));
    }


    @Test
    @Transactional
    public void getAllProjectsByObservationsIsEqualToSomething() throws Exception {
        // Initialize the database
        projectRepository.saveAndFlush(project);
        Observation observations = ObservationResourceIT.createEntity(em);
        em.persist(observations);
        em.flush();
        project.addObservations(observations);
        projectRepository.saveAndFlush(project);
        Long observationsId = observations.getId();

        // Get all the projectList where observations equals to observationsId
        defaultProjectShouldBeFound("observationsId.equals=" + observationsId);

        // Get all the projectList where observations equals to observationsId + 1
        defaultProjectShouldNotBeFound("observationsId.equals=" + (observationsId + 1));
    }


    @Test
    @Transactional
    public void getAllProjectsByFacultyIsEqualToSomething() throws Exception {
        // Initialize the database
        projectRepository.saveAndFlush(project);
        Faculty faculty = FacultyResourceIT.createEntity(em);
        em.persist(faculty);
        em.flush();
        project.setFaculty(faculty);
        projectRepository.saveAndFlush(project);
        Long facultyId = faculty.getId();

        // Get all the projectList where faculty equals to facultyId
        defaultProjectShouldBeFound("facultyId.equals=" + facultyId);

        // Get all the projectList where faculty equals to facultyId + 1
        defaultProjectShouldNotBeFound("facultyId.equals=" + (facultyId + 1));
    }


    @Test
    @Transactional
    public void getAllProjectsBySupervisorIsEqualToSomething() throws Exception {
        // Initialize the database
        projectRepository.saveAndFlush(project);
        Supervisor supervisor = SupervisorResourceIT.createEntity(em);
        em.persist(supervisor);
        em.flush();
        project.setSupervisor(supervisor);
        projectRepository.saveAndFlush(project);
        Long supervisorId = supervisor.getId();

        // Get all the projectList where supervisor equals to supervisorId
        defaultProjectShouldBeFound("supervisorId.equals=" + supervisorId);

        // Get all the projectList where supervisor equals to supervisorId + 1
        defaultProjectShouldNotBeFound("supervisorId.equals=" + (supervisorId + 1));
    }

    /**
     * Executes the search, and checks that the default entity is returned.
     */
    private void defaultProjectShouldBeFound(String filter) throws Exception {
        restProjectMockMvc.perform(get("/api/projects?sort=id,desc&" + filter))
            .andExpect(status().isOk())
            .andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
            .andExpect(jsonPath("$.[*].id").value(hasItem(project.getId().intValue())))
            .andExpect(jsonPath("$.[*].name").value(hasItem(DEFAULT_NAME)))
            .andExpect(jsonPath("$.[*].details").value(hasItem(DEFAULT_DETAILS.toString())))
            .andExpect(jsonPath("$.[*].objectives").value(hasItem(DEFAULT_OBJECTIVES.toString())))
            .andExpect(jsonPath("$.[*].problems").value(hasItem(DEFAULT_PROBLEMS.toString())));

        // Check, that the count call also returns 1
        restProjectMockMvc.perform(get("/api/projects/count?sort=id,desc&" + filter))
            .andExpect(status().isOk())
            .andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
            .andExpect(content().string("1"));
    }

    /**
     * Executes the search, and checks that the default entity is not returned.
     */
    private void defaultProjectShouldNotBeFound(String filter) throws Exception {
        restProjectMockMvc.perform(get("/api/projects?sort=id,desc&" + filter))
            .andExpect(status().isOk())
            .andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
            .andExpect(jsonPath("$").isArray())
            .andExpect(jsonPath("$").isEmpty());

        // Check, that the count call also returns 0
        restProjectMockMvc.perform(get("/api/projects/count?sort=id,desc&" + filter))
            .andExpect(status().isOk())
            .andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
            .andExpect(content().string("0"));
    }

>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
    @Test
    @Transactional
    public void getNonExistingProject() throws Exception {
        // Get the project
        restProjectMockMvc.perform(get("/api/projects/{id}", Long.MAX_VALUE))
            .andExpect(status().isNotFound());
    }

    @Test
    @Transactional
    public void updateProject() throws Exception {
        // Initialize the database
        projectService.save(project);

        int databaseSizeBeforeUpdate = projectRepository.findAll().size();

        // Update the project
        Project updatedProject = projectRepository.findById(project.getId()).get();
        // Disconnect from session so that the updates on updatedProject are not directly saved in db
        em.detach(updatedProject);
        updatedProject
            .name(UPDATED_NAME)
<<<<<<< HEAD
            .detials(UPDATED_DETIALS)
            .objective(UPDATED_OBJECTIVE)
            .problem(UPDATED_PROBLEM);
=======
            .details(UPDATED_DETAILS)
            .objectives(UPDATED_OBJECTIVES)
            .problems(UPDATED_PROBLEMS);
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity

        restProjectMockMvc.perform(put("/api/projects")
            .contentType(MediaType.APPLICATION_JSON)
            .content(TestUtil.convertObjectToJsonBytes(updatedProject)))
            .andExpect(status().isOk());

        // Validate the Project in the database
        List<Project> projectList = projectRepository.findAll();
        assertThat(projectList).hasSize(databaseSizeBeforeUpdate);
        Project testProject = projectList.get(projectList.size() - 1);
        assertThat(testProject.getName()).isEqualTo(UPDATED_NAME);
<<<<<<< HEAD
        assertThat(testProject.getDetials()).isEqualTo(UPDATED_DETIALS);
        assertThat(testProject.getObjective()).isEqualTo(UPDATED_OBJECTIVE);
        assertThat(testProject.getProblem()).isEqualTo(UPDATED_PROBLEM);
=======
        assertThat(testProject.getDetails()).isEqualTo(UPDATED_DETAILS);
        assertThat(testProject.getObjectives()).isEqualTo(UPDATED_OBJECTIVES);
        assertThat(testProject.getProblems()).isEqualTo(UPDATED_PROBLEMS);
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
    }

    @Test
    @Transactional
    public void updateNonExistingProject() throws Exception {
        int databaseSizeBeforeUpdate = projectRepository.findAll().size();

        // If the entity doesn't have an ID, it will throw BadRequestAlertException
        restProjectMockMvc.perform(put("/api/projects")
            .contentType(MediaType.APPLICATION_JSON)
            .content(TestUtil.convertObjectToJsonBytes(project)))
            .andExpect(status().isBadRequest());

        // Validate the Project in the database
        List<Project> projectList = projectRepository.findAll();
        assertThat(projectList).hasSize(databaseSizeBeforeUpdate);
    }

    @Test
    @Transactional
    public void deleteProject() throws Exception {
        // Initialize the database
        projectService.save(project);

        int databaseSizeBeforeDelete = projectRepository.findAll().size();

        // Delete the project
        restProjectMockMvc.perform(delete("/api/projects/{id}", project.getId())
            .accept(MediaType.APPLICATION_JSON))
            .andExpect(status().isNoContent());

        // Validate the database contains one less item
        List<Project> projectList = projectRepository.findAll();
        assertThat(projectList).hasSize(databaseSizeBeforeDelete - 1);
    }
}
