import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';

import { ISupervisor, Supervisor } from 'app/shared/model/supervisor.model';
import { SupervisorService } from './supervisor.service';
<<<<<<< HEAD
import { IFaculty } from 'app/shared/model/faculty.model';
import { FacultyService } from 'app/entities/faculty/faculty.service';
=======
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity

@Component({
  selector: 'jhi-supervisor-update',
  templateUrl: './supervisor-update.component.html',
})
export class SupervisorUpdateComponent implements OnInit {
  isSaving = false;
<<<<<<< HEAD
  faculties: IFaculty[] = [];

  editForm = this.fb.group({
    id: [],
    phoneNumber: [],
    faculties: [],
  });

  constructor(
    protected supervisorService: SupervisorService,
    protected facultyService: FacultyService,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}
=======

  editForm = this.fb.group({
    id: [],
    fullName: [],
    role: [],
    gender: [],
    email: [],
    phoneNumber: [],
  });

  constructor(protected supervisorService: SupervisorService, protected activatedRoute: ActivatedRoute, private fb: FormBuilder) {}
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ supervisor }) => {
      this.updateForm(supervisor);
<<<<<<< HEAD

      this.facultyService.query().subscribe((res: HttpResponse<IFaculty[]>) => (this.faculties = res.body || []));
=======
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
    });
  }

  updateForm(supervisor: ISupervisor): void {
    this.editForm.patchValue({
      id: supervisor.id,
<<<<<<< HEAD
      phoneNumber: supervisor.phoneNumber,
      faculties: supervisor.faculties,
=======
      fullName: supervisor.fullName,
      role: supervisor.role,
      gender: supervisor.gender,
      email: supervisor.email,
      phoneNumber: supervisor.phoneNumber,
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const supervisor = this.createFromForm();
    if (supervisor.id !== undefined) {
      this.subscribeToSaveResponse(this.supervisorService.update(supervisor));
    } else {
      this.subscribeToSaveResponse(this.supervisorService.create(supervisor));
    }
  }

  private createFromForm(): ISupervisor {
    return {
      ...new Supervisor(),
      id: this.editForm.get(['id'])!.value,
<<<<<<< HEAD
      phoneNumber: this.editForm.get(['phoneNumber'])!.value,
      faculties: this.editForm.get(['faculties'])!.value,
=======
      fullName: this.editForm.get(['fullName'])!.value,
      role: this.editForm.get(['role'])!.value,
      gender: this.editForm.get(['gender'])!.value,
      email: this.editForm.get(['email'])!.value,
      phoneNumber: this.editForm.get(['phoneNumber'])!.value,
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<ISupervisor>>): void {
    result.subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError(): void {
    this.isSaving = false;
  }
<<<<<<< HEAD

  trackById(index: number, item: IFaculty): any {
    return item.id;
  }

  getSelected(selectedVals: IFaculty[], option: IFaculty): IFaculty {
    if (selectedVals) {
      for (let i = 0; i < selectedVals.length; i++) {
        if (option.id === selectedVals[i].id) {
          return selectedVals[i];
        }
      }
    }
    return option;
  }
=======
>>>>>>> Initial version of pums generated by JHipster-6.10.5 with entity
}
